### ISSUE TITLE
单元测试添加h2

### ISSUE THREAD

**Issue by xuejmnet** [xuejmnet/easy-query#121]

**Comment by kuolemax** [comment]
现在支持h2了吗？我看好像没有一个sql-h2的包呀

**Comment by xuejmnet** [comment]
@kuolemax 可以的直接用mysql的包就可以了,因为整体没有任何依赖，所以easy-query目前可以看sql builder,并且h2兼容mysql语法,直接用mysql包就可以对接pgsql和h2数据库的 [性能测试](https://github.com/xuejmnet/easy-query-benchmark)  https://github.com/xuejmnet/easy-query-benchmark 这个项目是`Mybatis-Flex`的性能测试是h2数据库的,我直接在上面进行了测试对比

**Comment by xuejmnet** [comment]
后续出sql-h2的包也只是在当前语法上对h2的语法进行修改达到支持而已

**Comment by kuolemax** [comment]
好的，谢谢解答
