### ISSUE TITLE
并未发现此框架比mybatis“明显”更优的地方

### ISSUE THREAD

**Issue by cctyl** [xuejmnet/easy-query#164]
从 [流畅的orm让我发现我抵触的是mybatis而不是java](https://www.cnblogs.com/xuejiaming/p/17910064.html) 过来，大概看了下这个框架的思想，大抵是少写了sql。 这方面的话mybatisPlus 现在也可以做到的。
另外文章末尾提到jpa，我使用jpa也接近两年时间了，说方便确实有方便的地方，但是稍微复杂一些的逻辑，jpa来做就会出现很多坑。由于不能实现字段层面的控制，性能方面也比较差一些。选来选去，我觉得mybatisPlus 算是折中的方案。既有复杂sql能力，针对简单查询又有lambda的api支持。
我感觉这个框架大概相当于jpa+queryDsl，但是jpa 比较方便的 manyToMany, oneToMany,ManayToOne 也没体现在说明里，大部分还是单表（有联查但多表封装好像没有，不知是不是看漏了）。
各种方面来看，确实没有达到文章里所说的程度

**Comment by xuejmnet** [comment]
@cctyl 您好文章只是为了引流简要的说明这个框架的简单使用，你说的比mybatis优的地方我简单举几个例子

- 强类型sql支持join 支持子查询 支持嵌套
- 支持差异更新 并发更新
- 至于你说的jpa+querydsl我也支持支持一对一,一对多,多对一,多对多
- 分库分表自带比sharding-jdbc更优更轻量
- 数据库列加密存储支持高性能like索引
- 支持vo对象直接返回
- 动态条件 动态排序

以上都只是简单的列举了比mybatis-plus优的地方，如果你需要了解更多应该看文档而不是仅靠这篇博客
文档地址 https://xuejm.gitee.io/easy-query-doc/ 而且没有任何依赖比mybatis高一个数量级的性能更别提mybatis-plus了，你能忍受软删除在多表下面自己重复写deleted=0吗,所以mybatis-plus不支持join已经算不上一个合格的orm,不要说别用join这种蠢话,全程单表更是毫无逻辑可言

为什么没在博客里面体现是因为这篇博客已经不是第一篇了这篇博客主要展示新api的使用
