### ISSUE TITLE
oracle生成的sql默认带的""在oracle 19c 不识别

### ISSUE THREAD

**Issue by longlichenguang** [xuejmnet/easy-query#165]
select a."column1",a."column2" from  "table1" a 

SQL 错误 [904] [42000]: ORA-00904  a."column1" 标识符无效

select a.column1,a.column2  from  table1  a  正常

**Comment by xuejmnet** [comment]
@longlichenguang 您好因为带了双引号所以必须要大小写一致,您可以使用`nameConversion`来实现列同一转成大写,或者注解@Column来指定为大写 `upper_underlined`
<img width="1728" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/c7cfed8b-1031-4371-a6b7-6870942a4178">

**Comment by longlichenguang** [comment]
感谢,刚刚发现了
