### ISSUE TITLE
日志格式和mybatis日志一样

### ISSUE THREAD

**Issue by wm26hua** [xuejmnet/easy-query#198]
让日志格式和mybatis 格式一样，可以使用mybatis生态的一些sql插件,例如：
![image](https://github.com/xuejmnet/easy-query/assets/30584829/1073f245-301d-46ae-8e0d-71f5f8c15880)
现在就是参数中间逗号后面少个空格

**Comment by xuejmnet** [comment]
您可以自行替换框架的打印参数格式化SQLParameterPrintFormat![image](https://github.com/xuejmnet/easy-query/assets/18061232/0d503ec1-7591-4c3f-a017-55854ad9dcf9)

参考替换框架行为的默认类自己写一个替换就可以了，easy-query给足了使用者最大的diy方法

**Comment by wm26hua** [comment]
> 您可以自行替换框架的打印参数和SQLParameterPrintFormat。参考替换框架行为的默认类自己写一个替换就可以了，easy-query给足用户提供了最大的diy方法。![图像](https://private-user-images.githubusercontent.com/18061232/323697421-0d503ec1-7591-4c3f-a017-55854ad9dcf9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTU0MzAsIm5iZiI6MTcxMzc1NTEzMCwicGF0aCI6Ii8xODA2MTIzMi8zMjM2OTc0MjEtMGQ1MDNlYzEtNzU5MS00YzNmLWEwMTctNTU4NTRhZDlkY2Y5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwMzA1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTFkMjA1ODVkNjZjMTdkNzQzMGViNWM0MjM4YWYzODM5ZmYzNzAzYTI5NDkzZGRmZmU2NDJiMDI5ZTdlMTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D0m_zaq506V9FOKWzcNP7E2wkQ3bXSmdh9riUdoh8GI)

这不想你默认就是这个嘛

**Comment by wm26hua** [comment]
> 您可以自行替换框架的打印参数和SQLParameterPrintFormat。参考替换框架行为的默认类自己写一个替换就可以了，easy-query给用户提供了最大的diy方法。![图像](https://private-user-images.githubusercontent.com/18061232/323697421-0d503ec1-7591-4c3f-a017-55854ad9dcf9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NTU0MzAsIm5iZiI6MTcxMzc1NTEzMCwicGF0aCI6Ii8xODA2MTIzMi8zMjM2OTc0MjEtMGQ1MDNlYzEtNzU5MS00YzNmLWEwMTctNTU4NTRhZDlkY2Y5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQwMzA1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTFkMjA1ODVkNjZjMTdkNzQzMGViNWM0MjM4YWYzODM5ZmYzNzAzYTI5NDkzZGRmZmU2NDJiMDI5ZTdlMTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D0m_zaq506V9FOKWzcNP7E2wkQ3bXSmdh9riUdoh8GI)

这不就是想你默认就是这个样的嘛

**Comment by xuejmnet** [comment]
@wm26hua 可以那我默认和mybatis一样
下个版本

**Comment by xuejmnet** [comment]
@wm26hua 我看了一下好像不太好改建议还是你们改,因为我这边有上千个单元测试,如果默认的改了所有单元测试都要改我可以加一个默认的实现,你们要可以直接用但是默认还是现在这个 : (

**Comment by xuejmnet** [comment]
这边springboot添加了配置可选sqlParameterPrint:DEFAULT/MYBATIS

**Comment by wm26hua** [comment]
> @wm26hua 我看了一下好像不太好改建议还是你们改,因为我这边有上千个单元测试,如果默认的改了所有单元测试都要改我可以加一个默认的实现,你们要可以直接用但是默认还是现在这个 : (

这样啊，那好的

**Comment by xuejmnet** [comment]
1.10.62新增配置
<img width="1843" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/badaad42-14e3-4120-ad59-722669467904">

**Comment by wm26hua** [comment]
> 1.10.62新增配置 <img alt="image" width="1843" src="https://private-user-images.githubusercontent.com/18061232/324708716-badaad42-14e3-4120-ad59-722669467904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjA2NDcsIm5iZiI6MTcxMzkyMDM0NywicGF0aCI6Ii8xODA2MTIzMi8zMjQ3MDg3MTYtYmFkYWFkNDItMTRlMy00MTIwLWFkNTktNzIyNjY5NDY3OTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAwNTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYTAyOTA5YWY1YjM1MTkzYmI4ODIzMTk2ZjI2YzhmNWU4ZDI0NWY1Zjg4MzI5NzJmMThlODllYmMxNTY0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8QtkQSBlpntdr8AEwJUPl_cd7dTWT-VbrPzkrbozxg">

![image](https://github.com/xuejmnet/easy-query/assets/30584829/95660b6e-ddd9-4140-b455-543cc5af5c70)
可以了，可以了，非常感谢
