### ISSUE TITLE
支持pgsql

### ISSUE THREAD

**Issue by xuejmnet** [xuejmnet/easy-query#73]

**Comment by jasonfong11** [comment]
请问我已经指定了database=pgsql，然后打印出来的pgsql语句，怎么字段都带有符号，然后就导致语法错误了
![image](https://github.com/xuejmnet/easy-query/assets/63148087/d385f49a-a1db-4471-8aed-cb42b0f049ee)

**Comment by xuejmnet** [comment]
@jasonfong11 你确定指定了pgsql吗,这个是mysql方言引号,能发下你的配置文件和easy-query版本吗

**Comment by xuejmnet** [comment]
@jasonfong11 是springboot吗 
<img width="1558" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/ed4c06f2-ebcd-47e4-ad44-36e7da76953a">

pgsql的话生成的引号因该是双引号你具体看看配置文件 yml的话看下缩进

**Comment by jasonfong11** [comment]
找到问题了，因为我的项目是多数据源的，所以重新定义了一个easyQuery的Bean，指定了pg的数据源的时候，这个没有改成pg的
![image](https://github.com/xuejmnet/easy-query/assets/63148087/ef27050d-745d-4c54-84d0-f6764809bce3)
谢谢作者，反响很快！

**Comment by xuejmnet** [comment]
@jasonfong11 这种情况下你可能比如nameConversion需要配置一下不一定符合你的要求，还有一些额外的配置比如是否需要打印，具体可以看下文档的默认配置那一节正常只需要配置nameConversion就可以了，defaultConfiguration有replaceService或者addService可以替换默认的服务接口

**Comment by jasonfong11** [comment]
好的，我去研究一下

**Comment by xuejmnet** [comment]
@jasonfong11 
```java

EasyQueryBootstrapper.defaultBuilderConfiguration()
                .setDefaultDataSource(dataSource)
                .replaceService(DataSourceUnitFactory.class, SpringDataSourceUnitFactory.class)//支持springboot
                .replaceService(NameConversion.class, nameConversion)
                .replaceService(ConnectionManager.class, SpringConnectionManager.class)//支持springboot
```

<img width="849" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/e14657dd-4529-408f-b064-a72d43e4f783">

**Comment by xuejmnet** [comment]
@jasonfong11 不然在事务内crud会有问题

**Comment by jasonfong11** [comment]
好的，谢谢作者！！

**Comment by jasonfong11** [comment]
你好我还想问下，因为我是做地理数据相关的，pg的insert需要用到一些数据库函数比如"sde.st_geometry(:wkt,:srid)"，，同时我又不希望使用原生sql去插入，我试了一下全局拦截器好像满足不了，想问下这个框架有其他的方法吗

**Comment by xuejmnet** [comment]
@jasonfong11 insert的时候是吗，我后面看看

**Comment by jasonfong11** [comment]
对的，"sde.st_geometry(:wkt,:srid)"这个函数（wkt是用坐标构造出来的WKT格式的字符串，然后srid就是某个表中对应坐标系的id）主要是对pg中某个表进行地理信息更新，比如把某个点的xy坐标通过这个函数更新到shape字段中，现在的这个pgsql的insert，应该是没有对shape字段处理的
还有就是比如pgsql中，有objectid作为主键，但是insert的时候，如果希望主键自增填充，原生的pgsql是需要用到这个sde.next_rowid('sde',:layer)参数的，layer就是对应表名，这样insert的数据才能有objectid自增主键
附上我之前开发的一个sql工具类，一般如果用到地理数据开发，都是需要这样子去insert或者update pgsql的
![image](https://github.com/xuejmnet/easy-query/assets/63148087/a50cbb81-a226-4cee-9cf1-f19e58f21969)
希望对你有所帮助！

**Comment by xuejmnet** [comment]
@jasonfong11 问下你这个对应的sql生成的语句是
```sql
Insert Into layerName (objectId,shape,column1) values(sde.next_rowid('sde',?),sde.st_geometry(?,?))

参数 layerName,POINT (x y), 4326
```
是这样吗还是说`sde.next_rowid`是分两次的先select再insert对应的值?

**Comment by jasonfong11** [comment]
是的，就是这样
![image](https://github.com/xuejmnet/easy-query/assets/63148087/b8723c42-2e98-4c39-b7b3-8b9585abd538)

**Comment by xuejmnet** [comment]
@jasonfong11 
<img width="1070" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/5f9c7c54-d050-481a-aa04-a4ed2ff97edc">

<img width="979" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/846b2756-d538-4e9e-87cd-7475644b8d2d">

现在都已经支持了但是我觉得你这个有点奇怪,你应该是insert自动调用 `st_geometry`那么查询呢,你怎么办有对应的反解析吗

**Comment by xuejmnet** [comment]
> 查询也有对应的sde函数的，比如sde.astext即把几何解析成字符串，像一些地理关系判断比如相交之类的，也是需要通过这些函数来计算，其实就是需要自定义列，我看之前的好像不支持，所以才提出来

已经在做了，我是否可以理解为和mysql的aes加密解密方法一样是一对方法是吧 查询用解密，插入新增和where条件用加密是吧

**Comment by jasonfong11** [comment]
对！就是类似这种，其实直接写原生sql也可以，但是我自己觉得既然用上了框架，并且在pg里面，一般实体类的insert或者update都会带着这些函数，所以我想要在不放弃使用上强类型的情况下，也可以完成这种自定义列的效果

**Comment by xuejmnet** [comment]
@jasonfong11 已经支持
<img width="1210" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/35dc4baf-bfb4-44be-8a5d-7be08de382d1">
具体可以参考单元测试,您这边应该还差一个主键自动生成的功能吧,就是说你的主键插入的时候是自定义的,查询还是按原类型的功能,应该还差一个这个后续我回家一下,其他字段已经支持select insert update where 默认自定义支持,单元测试室mysql的aes加解密
<img width="1411" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/40755e34-5ea3-4e25-8ada-f1477fe1a5b9">

**Comment by xuejmnet** [comment]
@jasonfong11 最新版本已经发布1.3.7 支持自定义increment column
具体可以参考单元测试
<img width="1112" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/aa764886-9f27-4946-8162-e51291da4fd8">

<img width="1048" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/e76a4320-852b-4387-ad4c-91d3d3ad965c">


<img width="1007" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/f1da225c-21e1-4db1-a4c6-8df048a3a943">


<img width="1434" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/d8bb1b34-bef1-4ec8-8629-0ee14179a5f8">

**Comment by jasonfong11** [comment]
![image](https://github.com/xuejmnet/easy-query/assets/63148087/3f44a125-4796-4e7f-9221-bdfa2921e565)
这个判断是不是写错了
![image](https://github.com/xuejmnet/easy-query/assets/63148087/b734a6c6-7c7d-4647-8acc-393572c75c90)
还有个问题，就是这里好像没有自动装配上我自己实现了ColumnValueSQLConverter和IncrementSQLColumnGenerator的类
会导致这个报错
![image](https://github.com/xuejmnet/easy-query/assets/63148087/63b18c1e-4bd4-40ef-9c09-56925acbe160)
发现columnValueSQLConverterMap在执行easyQuery初始化的时候都是空的
我自己定义了一个config，然后手动调用apply方法才可以
![image](https://github.com/xuejmnet/easy-query/assets/63148087/c5729972-2b4f-4e37-b7f1-240f239a3fe7)

**Comment by xuejmnet** [comment]
@jasonfong11 抱歉啊刚才中午没看到,你说的问题升级版本就可以了,关于自动装配是如果你是默认的一个easyQuery是会自动装配的,但是你是自己构建的bean那么就没办法,如果你不是自己构建的easyQuery那么通过添加@Component即可
<img width="954" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/631b5457-71e6-4906-a713-7016b94f3c38">

这个是默认的装载

**Comment by xuejmnet** [comment]
@jasonfong11 就是default的easyQuery,由sql-springboot-starter包自行构建的只需要@Component,如果不是那么就是可以手动创建
<img width="1391" alt="image" src="https://github.com/xuejmnet/easy-query/assets/18061232/af6fb261-f9d2-48f5-92dc-0a141670ac2f">

**Comment by xuejmnet** [comment]
@jasonfong11 当存在多个easyquery的情况下框架将不知道如何注册,或者说肯定不是所有的easyQuery都需要注册,所以这种情况下建议按需注册自行处理

**Comment by jasonfong11** [comment]
这里属性名风格，转换小驼峰的方法用错了
![image](https://github.com/xuejmnet/easy-query/assets/63148087/55fc6396-5e0a-49c2-8784-f1e00151820f)

**Comment by xuejmnet** [comment]
> 这里属性名风格，转换小驼峰的方法用错了 ![image](https://user-images.githubusercontent.com/63148087/260895188-55fc6396-5e0a-49c2-8784-f1e00151820f.png)

十分感谢，我会在下个版本修复并将这个问题加入到单元测试里面：）,如果你现在有用那么就直接替换掉我的接口即可,springboot参考 https://xuejm.gitee.io/easy-query-doc/guide/config/replace-configure.html#%E8%87%AA%E5%AE%9A%E4%B9%89nameconversion
当然这个是适合springboot默认构建的bean如果不是那么就直接在构建的时候替换掉对应的服务即可

```java
 EasyQueryClient easyQueryClient = EasyQueryBootstrapper.defaultBuilderConfiguration()
                .setDefaultDataSource(dataSource)
                .optionConfigure(op -> {
                    op.setDeleteThrowError(true);//设置不允许物理删除
                    op.setPrintSql(true);//设置以log.info模式打印执行sql信息
                    ......//此处用于配置系统默认配置选项
                })
                .useDatabaseConfigure(new MySQLDatabaseConfiguration())//设置方言语法等为mysql的
                .replaceService(NameConversion.class, MyNameConversion.class)//放在最后面可以替换掉前面所有方法
                .build();
```

**Comment by jasonfong11** [comment]
如果是我自己构建easyQuery的bean，好像实现的那些自定义列的convert都不会自动注入？需要自己在构建的方法里面调用apply，是我用的姿势不正确吗

**Comment by xuejmnet** [comment]
> 如果是我自己构建easyQuery的bean，好像实现的那些自定义列的convert都不会自动注入？需要自己在构建的方法里面调用apply，是我用的姿势不正确吗

是的自己构建的bean就自己apply，通过easyQuery或者client获取QueryRuntimeContext下的QueryConfiguration，因为如果自动注入会有个问题就是框架不知道别的easyQuery是否需要，所以只有默认的给你注入别的都需要手动处理
